// 사용자 주소 입력 데이터
export const Region = [
  {
    id: 1,
    value: '서울특별시',
    city: [],
  },
  {
    id: 2,
    value: '부산광역시',
    city: [],
  },
  {
    id: 3,
    value: '대구광역시',
    city: [],
  },
  {
    id: 4,
    value: '인천광역시',
    city: [],
  },
  {
    id: 5,
    value: '광주광역시',
    city: [],
  },
  {
    id: 6,
    value: '대전광역시',
    city: [],
  },
  {
    id: 7,
    value: '울산광역시',
    city: [],
  },
  {
    id: 8,
    value: '세종특별자치시',
    city: [],
  },
  {
    id: 9,
    value: '경기도',
    city: [
      {id: 1, value: '수원시'},
      {id: 2, value: '고양시'},
      {id: 3, value: '용인시'},
      {id: 4, value: '성남시'},
      {id: 5, value: '부천시'},
      {id: 6, value: '화성시'},
      {id: 7, value: '안산시'},
      {id: 8, value: '남양주시'},
      {id: 9, value: '안양시'},
      {id: 10, value: '평택시'},
      {id: 11, value: '시흥시'},
      {id: 12, value: '파주시'},
      {id: 13, value: '의정부시'},
      {id: 14, value: '김포시'},
      {id: 15, value: '광주시'},
      {id: 16, value: '광명시'},
      {id: 17, value: '군포시'},
      {id: 18, value: '하남시'},
      {id: 19, value: '오산시'},
      {id: 20, value: '양주시'},
      {id: 21, value: '이천시'},
      {id: 22, value: '구리시'},
      {id: 23, value: '안성시'},
      {id: 24, value: '포천시'},
      {id: 25, value: '의왕시'},
      {id: 26, value: '과천시'},
      {id: 27, value: '여주시'},
      {id: 28, value: '동두천시'},
      {id: 29, value: '양평군'},
      {id: 30, value: '가평군'},
      {id: 31, value: '연천군'},
    ],
  },
  {
    id: 10,
    value: '강원도',
    city: [
      {id: 1, value: '춘천시'},
      {id: 2, value: '원주시'},
      {id: 3, value: '강릉시'},
      {id: 4, value: '동해시'},
      {id: 5, value: '태백시'},
      {id: 6, value: '속초시'},
      {id: 7, value: '삼척시'},
      {id: 8, value: '홍천군'},
      {id: 9, value: '횡성군'},
      {id: 10, value: '영월군'},
      {id: 11, value: '평창군'},
      {id: 12, value: '정선군'},
      {id: 13, value: '철원군'},
      {id: 14, value: '화천군'},
      {id: 15, value: '양구군'},
      {id: 16, value: '인제군'},
      {id: 17, value: '고성군'},
      {id: 18, value: '양양군'},
    ],
  },
  {
    id: 11,
    value: '충청북도',
    city: [
      {id: 1, value: '청주시'},
      {id: 2, value: '충주시'},
      {id: 3, value: '제천시'},
      {id: 4, value: '보은군'},
      {id: 5, value: '옥천군'},
      {id: 6, value: '영동군'},
      {id: 7, value: '증평군'},
      {id: 8, value: '진천군'},
      {id: 9, value: '괴산군'},
      {id: 10, value: '음성군'},
      {id: 11, value: '단양군'},
    ],
  },
  {
    id: 12,
    value: '충청남도',
    city: [
      {id: 1, value: '천안시'},
      {id: 2, value: '공주시'},
      {id: 3, value: '보령시'},
      {id: 4, value: '아산시'},
      {id: 5, value: '서산시'},
      {id: 6, value: '논산시'},
      {id: 7, value: '계룡시'},
      {id: 8, value: '당진시'},
      {id: 9, value: '금산군'},
      {id: 10, value: '부여군'},
      {id: 11, value: '서천군'},
      {id: 12, value: '청양군'},
      {id: 13, value: '홍성군'},
      {id: 14, value: '예산군'},
      {id: 15, value: '태안군'},
    ],
  },
  {
    id: 13,
    value: '전라북도',
    city: [
      {id: 1, value: '전주시'},
      {id: 2, value: '군산시'},
      {id: 3, value: '익산시'},
      {id: 4, value: '정읍시'},
      {id: 5, value: '남원시'},
      {id: 6, value: '김제시'},
      {id: 7, value: '완주군'},
      {id: 8, value: '진안군'},
      {id: 9, value: '무주군'},
      {id: 10, value: '장수군'},
      {id: 11, value: '임실군'},
      {id: 12, value: '순창군'},
      {id: 13, value: '고창군'},
      {id: 14, value: '부안군'},
    ],
  },
  {
    id: 14,
    value: '전라남도',
    city: [
      {id: 1, value: '목포시'},
      {id: 2, value: '여수시'},
      {id: 3, value: '순천시'},
      {id: 4, value: '나주시'},
      {id: 5, value: '광양시'},
      {id: 6, value: '담양군'},
      {id: 7, value: '곡성군'},
      {id: 8, value: '구례군'},
      {id: 9, value: '고흥군'},
      {id: 10, value: '보성군'},
      {id: 11, value: '화순군'},
      {id: 12, value: '장흥군'},
      {id: 13, value: '강진군'},
      {id: 14, value: '해남군'},
      {id: 15, value: '영암군'},
      {id: 16, value: '무안군'},
      {id: 17, value: '함평군'},
      {id: 18, value: '영광군'},
      {id: 19, value: '장성군'},
      {id: 20, value: '완도군'},
      {id: 21, value: '진도군'},
      {id: 22, value: '신안군'},
    ],
  },
  {
    id: 15,
    value: '경상북도',
    city: [
      {id: 1, value: '포항시'},
      {id: 2, value: '경주시'},
      {id: 3, value: '김천시'},
      {id: 4, value: '안동시'},
      {id: 5, value: '구미시'},
      {id: 6, value: '영주시'},
      {id: 7, value: '영천시'},
      {id: 8, value: '상주시'},
      {id: 9, value: '문경시'},
      {id: 10, value: '경산시'},
      {id: 11, value: '군위군'},
      {id: 12, value: '의성군'},
      {id: 13, value: '청송군'},
      {id: 14, value: '영양군'},
      {id: 15, value: '영덕군'},
      {id: 16, value: '청도군'},
      {id: 17, value: '고령군'},
      {id: 18, value: '성주군'},
      {id: 19, value: '칠곡군'},
      {id: 20, value: '예천군'},
      {id: 21, value: '봉화군'},
      {id: 22, value: '울진군'},
      {id: 23, value: '울릉군'},
    ],
  },
  {
    id: 16,
    value: '경상남도',
    city: [
      {id: 1, value: '창원시'},
      {id: 2, value: '진주시'},
      {id: 3, value: '통영시'},
      {id: 4, value: '사천시'},
      {id: 5, value: '김해시'},
      {id: 6, value: '밀양시'},
      {id: 7, value: '거제시'},
      {id: 8, value: '양산시'},
      {id: 9, value: '의령군'},
      {id: 10, value: '함안군'},
      {id: 11, value: '창녕군'},
      {id: 12, value: '고성군'},
      {id: 13, value: '남해군'},
      {id: 14, value: '하동군'},
      {id: 15, value: '산청군'},
      {id: 16, value: '함양군'},
      {id: 17, value: '거창군'},
      {id: 18, value: '합천군'},
    ],
  },
  {
    id: 17,
    value: '제주특별자치도',
    city: [
      {id: 1, value: '제주시'},
      {id: 1, value: '서귀포시'},
    ],
  },
];
