export const incheonDummy = [
  {
    id: 1,
    name: '맛동산',
    meter: 1000,
    now: '인천광역시 동구',
    profile: require('../../assets/gyeryongMountain.jpg'),
    fire: require('../../assets/fire.png'),
    cnt: 300,
  },
  {
    id: 2,
    name: '화산',
    meter: 1000,
    now: '인천광역시 남구',
    profile: require('../../assets/jjang.png'),
    fire: require('../../assets/fire.png'),
    cnt: 100,
  },
  {
    id: 3,
    name: '계산',
    meter: 1000,
    now: '인천광역시 부평구',
    profile: require('../../assets/you.png'),
    fire: require('../../assets/fire.png'),
    cnt: 300,
  },
  {
    id: 4,
    name: '해산',
    meter: 1000,
    now: '인천광역시 계양구',
    profile: require('../../assets/mountainFour.png'),
    fire: require('../../assets/fire.png'),
    cnt: 100,
  },
  {
    id: 5,
    name: '확산',
    meter: 1000,
    now: '인천광역시 남동구 ',
    profile: require('../../assets/mountainThree.png'),
    fire: require('../../assets/fire.png'),
    cnt: 100,
  },
  {
    id: 6,
    name: '수산',
    meter: 1000,
    now: '인천광역시 연수구',
    profile: require('../../assets/mountainTwo.png'),
    fire: require('../../assets/fire.png'),
    cnt: 10,
  },
  {
    id: 7,
    name: '물산',
    meter: 1000,
    now: '인천광역시 강화군',
    profile: require('../../assets/mountainOne.png'),
    fire: require('../../assets/fire.png'),
    cnt: 300,
  },
];

export const SeoulDummy = [
  {
    id: 1,
    name: '맛동산',
    meter: 1000,
    now: '서울특별시 강서구',
    profile: require('../../assets/gyeryongMountain.jpg'),
    fire: require('../../assets/fire.png'),
    cnt: 300,
  },
  {
    id: 2,
    name: '화산',
    meter: 1000,
    now: '서울특별시 강서구',
    profile: require('../../assets/jjang.png'),
    fire: require('../../assets/fire.png'),
    cnt: 100,
  },
  {
    id: 3,
    name: '계산',
    meter: 1000,
    now: '서울특별시 송파구',
    profile: require('../../assets/you.png'),
    fire: require('../../assets/fire.png'),
    cnt: 300,
  },
  {
    id: 4,
    name: '해산',
    meter: 1000,
    now: '서울특별시 동작구',
    profile: require('../../assets/mountainFour.png'),
    fire: require('../../assets/fire.png'),
    cnt: 100,
  },
  {
    id: 5,
    name: '확산',
    meter: 1000,
    now: '서울특별시 노원구',
    profile: require('../../assets/mountainThree.png'),
    fire: require('../../assets/fire.png'),
    cnt: 100,
  },
  {
    id: 6,
    name: '수산',
    meter: 1000,
    now: '서울특별시 강남구',
    profile: require('../../assets/mountainTwo.png'),
    fire: require('../../assets/fire.png'),
    cnt: 10,
  },
  {
    id: 7,
    name: '물산',
    meter: 1000,
    now: '서울특별시 강남구',
    profile: require('../../assets/mountainOne.png'),
    fire: require('../../assets/fire.png'),
    cnt: 300,
  },
];

export const DummyMountain = [
  {
    id: 1,
    name: '계룡산',
    meter: 800,
    now: '대전광역시 유성구',
    profile: require('../../assets/gyeryongMountain.jpg'),
    fire: require('../../assets/fire.png'),
    cnt: 300,
  },
  {
    id: 2,
    name: '식장산',
    meter: 1200,
    now: '대전광역시 동구',
    profile: require('../../assets/mountainOne.png'),
    fire: require('../../assets/fire.png'),
    cnt: 200,
  },
  {
    id: 3,
    name: '봉황산',
    meter: 300,
    now: '충청남도 보령시',
    profile: require('../../assets/mountainTwo.png'),
    fire: require('../../assets/fire.png'),
    cnt: 450,
  },
  {
    id: 4,
    name: '우산',
    meter: 1004,
    now: '안알려줌 가짜임',
    profile: require('../../assets/mountainThree.png'),
    fire: require('../../assets/fire.png'),
    cnt: 0,
  },
  {
    id: 5,
    name: '염산',
    meter: 1818,
    now: '염산은 무서움',
    profile: require('../../assets/mountainFour.png'),
    fire: require('../../assets/fire.png'),
    cnt: 0,
  },
  {
    id: 6,
    name: '미국산',
    meter: 1234,
    now: '미국산 소고기나빠',
    profile: require('../../assets/jjang.png'),
    fire: require('../../assets/fire.png'),
    cnt: 0,
  },
];
